### ISSUE TITLE
WebMock adapter

### ISSUE THREAD

**Issue by hc2p** [igrigorik/http-2#100]
it seems like there is no [WebMock](https://github.com/bblimke/webmock) adapter for this gem yet. Does anyone out there has something in the making?

Background: We are using RSpec with VCR and can't record http-2 connections

**Comment by igrigorik** [comment]
Note that we (http-2) do not provide a functional HTTP client implementation. Our goal is to provide the low-level bits for dealing with encoding, decoding, and stream management, which can then be used to build clients on top. 

As such, I don't think this is the right level of abstraction to think about WebMock..?

**Comment by hc2p** [comment]
right, totally makes sense. Thanks for the clarification
