### ISSUE TITLE
Naming of gem

### ISSUE THREAD

**Issue by ioquatix** [igrigorik/http-2#102]
This gem is awesome. Sorry for being super pedantic, but why not just call it `http2`?

It would make more sense.

`require 'http2'` would import a module called `HTTP2`.

No need to have `2.rb` and `http/2/*.rb`.

I think it's fun that you can write `require 'http/2'`, but it doesn't match up with the name of the module, nor is it typical.

Thoughts?

**Comment by igrigorik** [comment]
All good points. The counter is: "http/x" is the name convention in http-land.

There is no right or wrong here, and I don't think we stand to gain anything by changing names at this point.

**Comment by ioquatix** [comment]
> All good points. The counter is: "http/x" is the name convention in http-land.

I don't see any gem named `http-1` - where are you getting this convention from?

The name convention I suggested is derived from RubyGems recommendations: http://guides.rubygems.org/name-your-gem/

> There is no right or wrong here, and I don't think we stand to gain anything by changing names at this point.

What you stand to gain is better consistency with official RubyGems naming conventions. There is value in this.

**Comment by igrigorik** [comment]
> I don't see any gem named http-1 - where are you getting this convention from?

I'm not talking Ruby, rather:

- https://http2.github.io/
- https://en.wikipedia.org/wiki/HTTP/2
- http://httpwg.org/specs/rfc7540.html

**Comment by ioquatix** [comment]
Well, I respect your choices, but I think it's wrong to ignore the RubyGems conventions.

**Comment by nateberkopec** [comment]
@ioquatix what does it matter if someone already has the `http2` gem name?

**Comment by ioquatix** [comment]
Well, in the past, I usually check if there is a naming conflict. In the case there is, I normally check if the project is alive or not. If it's alive, I opt for a different name, usually totally different so as to avoid any confusion.

If it's not alive, I normally try to contact the author and ask them. It depends on my goals, but I normally do something on the continuum of 1/ offer to maintain the existing code base and add the functionality I want or 2/ reuse the name but scrap the existing code (bump major version if required).

I didn't even know a gem called `http2` existed, but yes, I can see how now the situation is very confusing for everyone.

The `http2` gem defines a module `class Http2` so only by luck (and poor naming on the part of the original code since abbreviations should be capitalised IMHO) would these two gems not completely self-destruct if used together for some reason.

It might not be obvious where this is a problem - it becomes a problem when you have these dependencies several levels deep in different branches of your dependency tree. You may not even realise there is an issue until too late. But, IMHO, people should abide by the RubyGems naming convention to avoid namespace collisions.

Just my 2c.
