### ISSUE TITLE
@streams_recently_closed update failing under multiple threads

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#103]
I'm referring specifically to [this snippet](https://github.com/igrigorik/http-2/blob/master/lib/http/2/connection.rb#L657-L662), which under certain circumstances (multiple requests arrive and are scheduled to different threads) causes the following error:

```
E, [2017-09-17T20:17:15.872990 #23156] ERROR -- : RuntimeError: can't add a new key into hash during iteration
E, [2017-09-17T20:17:15.873078 #23156] ERROR -- : /Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/connection.rb:662:in `block in activate_stream'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/emitter.rb:22:in `block in once'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/emitter.rb:34:in `block in emit'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/emitter.rb:33:in `delete_if'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/emitter.rb:33:in `emit'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/stream.rb:567:in `complete_transition'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/stream.rb:610:in `manage_state'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/flow_buffer.rb:55:in `send_data'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/stream.rb:133:in `send'
/Projects/palanca/.bundle/ruby/2.3.0/gems/http-2-0.8.4/lib/http/2/stream.rb:193:in `data'
```

Now, one can try to rewrite that particular snippet, but I'd say that, under these circumstances, it's hard not to replace that bit and introduce a race condition, at least without adding a lock.

My question would be more, since the public API here is very limited (`#<<` and `#headers` and `#data`) and one interacts more through callbacks which are indirectly called, should one at best handle all requests from one connection in the same thread, or could one get away with locking a few (if not all) of those public API calls?

Currently as it is, a connection cannot be shared across threads due to the error described above though.

**Comment by igrigorik** [comment]
> should one at best handle all requests from one connection in the same thread, or could one get away with locking a few (if not all) of those public API calls?

Yes, that would be my recommendation. One "main" worker thread that's responsible for processing all inbound and outbound protocol work, with workers doing the app-level request/response processing.

**Comment by HoneyryderChuck** [comment]
> Yes, that would be my recommendation.

Yup, thought so. I was thinking of using the "one reactor thread for wait/worker threads for read/write/process", which works well for HTTP 1.0/1.1, but this is only due to HOL. Due to HTTP2 multiplexing, this doesn't seem possible (I don't know what kind of optimizations the C-based web-servers have regarding this though). 

Thanks for the answer. I'll close the ticket.
