### ISSUE TITLE
Client failing to GET https://nghttp2.org

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#106]
While trying to debug the other issue reported, I've realized that I can't request a publicly accessible website with the simple client (in this case, `https://nghttp2.org`). Just try the example client:

```
>  ruby example/client.rb https://nghttp2.org
Sending HTTP 2.0 request
Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
Sent frame: {:type=>:headers, :flags=>[:end_headers, :end_stream], :payload=>[[":scheme", "https"], [":method", "GET"], [":authority", "nghttp2.org:443"], [":path", ""], ["accept", "*/*"]], :stream=>1}
[Stream 1]: closing client-end of the stream
Received frame: {:length=>18, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100], [:settings_initial_window_size, 1048576], [:settings_header_table_size, 8192]]}
Sent frame: {:type=>:settings, :stream=>0, :payload=>[], :flags=>[:ack]}
Received frame: {:length=>0, :type=>:settings, :flags=>[:ack], :stream=>0, :payload=>[]}
Received frame: {:length=>4, :type=>:rst_stream, :flags=>[], :stream=>1, :error=>:protocol_error}
[Stream 1]: stream closed

```

The difference I see to the frame output from `nghttp`is that the latter does the whole "connection dance" before sending the headers frame (send/receive settings and ack, send priorities...).

**Comment by igrigorik** [comment]
@HoneyryderChuck did you try https://github.com/igrigorik/http-2/pull/44/files? Does that help?

**Comment by HoneyryderChuck** [comment]
TBH I don't remember, it might be that this was caused by some local change, I could retry reproducing it again later, as I'm on holidays now. However,  my client lib is tested against nghttp2.org, and it works well, so feel free to close the issue.

**Comment by HoneyryderChuck** [comment]
Did this again, and saw the error again. And then I reminded that I saw this before. Key is: 

```
Sent frame: {:type=>:headers, :flags=>[:end_headers, :end_stream], :payload=>[[":scheme", "https"], [":method", "GET"], [":authority", "nghttp2.org:443"], [":path", ""], ["accept", "*/*"]], :stream=>1}
```

The headers frame can't generate the `:path` pseudo-header with an empty string. Either `http-2` is doing something wrong by encoding the empty string wrong, or it has to make sure that the client passes something to the path. Either way, I think this is something that should be validated. What do you think @igrigorik?

**Comment by igrigorik** [comment]
Oh, doh. That's a simple fix. The example you're passing in doesn't have a path and that's what gets passed through, we should do a check for empty path and pass in "/" instead. 

https://github.com/igrigorik/http-2/blob/master/example/client.rb#L95

If you query `ruby example/client.rb https://nghttp2.org/`, everything works as expected.

**Comment by HoneyryderChuck** [comment]
@igrigorik that's what I meant, in a convoluted way :) I just wanted to double-check whether this check should be of the library, or it should off-loaded to the end-user. I'll see about adding a fix.

**Comment by igrigorik** [comment]
The client is an example, and it's not meant to be a production-quality CLI tool.. That said, this is a common gotcha and something we should address in the client. Thanks for taking this on!
