### ISSUE TITLE
max concurrent streams: when to do when reached

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#109]
I'm hitting a limit in a test I'm doing locally, specifically when I want to get a number of requests greater than max concurrent streams. Like, when the current defaults, if I send 102 requests on the same connection when the limit is 100, it handles the first 100, and it doesn't send any type of response from the server for the last 2 (in my specific case, the client hangs waiting for those 2 streams that never come). 

First, I thought that this meant "streams can handle only X concurrent, when one closes, send the next one". However, this is not working like this, because if I set the 101th stream when one of the first 100 streams closes (`:close` callback), it will also hang. 

Is this a bug, or a feature? Because there are a few things I was expecting both from the server (`https://nghttp2.org`, in this case) and the client, namely:

* the server could send a `GOAWAY` for the exceeding streams (`REFUSED_STREAM` maybe?)
* the client could fail when handling a number of concurrent streams greater than MAX
* or, the client could fails after handling MAX streams
* (after any of the above) the client would renegotiate settings with the server, thereby "resetting" the connection.

None of the above are backed by the spec (they're all expectations of mine), but I'll have a look to see what was to be expected in this case.

**Comment by igrigorik** [comment]
This sounds like a bug. The intended behavior is like you described. 

https://github.com/igrigorik/http-2/blob/bf4b930c19934521bb0ffcfa19486ff7e415ed55/spec/connection_spec.rb#L73

Any chance you can wire up a spec that can reproduce this failure?

**Comment by HoneyryderChuck** [comment]
Sure. I'll come up with something before the end of the week

**Comment by HoneyryderChuck** [comment]
This is my test script:

```ruby
require "http/2"
require "logger"
require "socket"
require "uri"

URLS  = %w[http://nghttp2.org http://nghttp2.org/blog/] * 51
done = URLS.size
uri = URI(URLS.first)
sock = TCPSocket.new(uri.host, uri.port)
if uri.scheme == 'https'
  require 'openssl'
  ctx = OpenSSL::SSL::SSLContext.new
  ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE

  # For ALPN support, Ruby >= 2.3 and OpenSSL >= 1.0.2 are required

  ctx.alpn_protocols = %w(h2)
  ctx.alpn_select_cb = lambda do |protocols|
    puts "ALPN protocols supported by server: #{protocols}"
    'h2' if protocols.include? 'h2' 
  end

  sock = OpenSSL::SSL::SSLSocket.new(sock, ctx)
  sock.sync_close = true
  sock.hostname = uri.hostname
  sock.connect

  if sock.alpn_protocol != 'h2' 
    puts "Failed to negotiate via ALPN"
    exit
  end
end


conn = HTTP2::Client.new
write_buffer = +""
conn.on(:frame) do |bytes|
  write_buffer << bytes
end
conn.on(:frame_sent) do |frame|
  puts "Sent frame: #{frame.inspect}"
end
conn.on(:frame_received) do |frame|
  if frame[:type] == :data
    puts "Received data frame: #{frame[:payload].bytesize}"
  else
    puts "Received frame: #{frame.inspect}"
  end
end
conn.on(:promise, &:refuse)

URLS.each do |url|
  uri = URI(url)
  stream = conn.new_stream
  log = Logger.new(stream.id.to_s)
  
  stream.on(:close) do
    log.info 'stream closed'
    done -= 1
    puts "done: #{done}"
  end
  
  stream.on(:half_close) do
    log.info 'closing client-end of the stream'
  end
  
  stream.on(:headers) do |h|
    log.info "response headers: #{h}"
  end
  
  stream.on(:data) do |d|
#    log.info "response data chunk: <<#{d.bytesize} bytes>>"
  end
  
  #stream.on(:altsvc) do |f|
  #  log.info "received ALTSVC #{f}"
  #end
 
  head = {
    ':scheme' => uri.scheme,
    ':method' => 'GET',
    ':authority' => uri.host,
    ':path' => uri.path.empty? ? '/' : uri.path,
    'accept' => '*/*',
    'user-agent' => 'anon.rb' ,
  }
  
  stream.headers(head, end_stream: true)
end


loop do
  return if done.zero?
  readers, writers = IO.select([sock], [sock])
  readers.each do |r|
    loop do 
      buf = r.read_nonblock(16_384, exception: false)
      case buf
      when :wait_readable
        break
      when nil
        r.close
      else
        conn << buf
      end
    end
  end if readers
  writers.each do |w|
    loop do 
      nsiz = w.write_nonblock(write_buffer, exception: false)
      case nsiz
      when :wait_writable, 0
        break
      when nil
        w.close
      else
        write_buffer.slice!(0, nsiz)
      end
    end
  end if writers
end
```

**Comment by HoneyryderChuck** [comment]
I'm not being able to reproduce where it's hanging, but you can already see that the server is refusing the 2 extra streams, instead of the client not sending them and failing early. 

Question is, what's the strategy, when it reaches the limit?

**Comment by HoneyryderChuck** [comment]
So, a few conclusions:

* that my example hangs has nothing to do with `http-2`; I wasn't simply handling the `:rst_stream` error, and was therefore waiting for a response to the refused stream; after doing this, the 2 extra streams were handled as "failed responses".
* `http-2` doesn't properly handle "too many streams", because in my case, I'm creating the streams before the "handshake" is established, and the client and server exchange the settings. This means that max streams is 2 ** 14. 

I don't know whether one should consider it a bug, as spec-wise, it's correct, and the server does refuse the extra streams. Maybe it could be more explicit with the error type (I get `:rst_stream`, but it could be `:too_many_streams`?), but for this to happen, the error should be part of the spec and thrown by the server. From the application side, I think I could add a retry mechanism to refused streams to circumvent this.

**Comment by igrigorik** [comment]
> http-2 doesn't properly handle "too many streams", because in my case, I'm creating the streams before the "handshake" is established, and the client and server exchange the settings. This means that max streams is 2 ** 14.

If you inject a delay and wait for the settings exchange to complete, what happens?

> Maybe it could be more explicit with the error type (I get :rst_stream, but it could be :too_many_streams?), but for this to happen, the error should be part of the spec and thrown by the server. From the application side, I think I could add a retry mechanism to refused streams to circumvent this.

If you get [REFUSED_STREAM](http://httpwg.org/specs/rfc7540.html#REFUSED_STREAM) you can safely retry the request.

**Comment by HoneyryderChuck** [comment]
> If you inject a delay and wait for the settings exchange to complete, what happens?

The expected error, the client will fail, as I started too many streams.

I've implemented a retry mechanism for refused streams. Maybe by limiting the send buffer in the future (still TODO) will prevent this from happening at all.

I'll close the issue, as I think that this is an application issue.
