### ISSUE TITLE
remove deep_dup usage in tests, use helper methods instead

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#117]
Coming from https://github.com/igrigorik/http-2/pull/116#issuecomment-362048852

The deep_dup method (the same as in ActiveSupport) shows some edge cases where it's mutating the hashes used in the tests. Whether this is a ruby bug or not is not the matter, but this could be fixed by relying on helper methods instead, which could be injected in the describe blocks where they are used.

**Comment by ioquatix** [comment]
I don't know the full context of this issue, but rather than using dup, why not just have separate specs?

**Comment by HoneyryderChuck** [comment]
I found a weird edge case when doing the mentioned PR, where an error would arise depending of the test order of interpretation, which was non-trivial. The main culprit was that all tests were using a deep_dup copy of those frame hashes, and these weren't really deep-dup'ed (because ruby :) ). 

Long story short, one should be using fresh hashes for each test instead of relying on deep_dup quirks. And helper methods should be the way to go.

**Comment by ioquatix** [comment]
To be honest, the structure of this gem and the specs leaves a lot to be desired, I hope I can spend some time on improving it slowly with small steps.

**Comment by ioquatix** [comment]
As I'm sure you already are, I welcome you to improve the specs, as I have been doing recently.
