### ISSUE TITLE
Is it okay to have multiple `set-cookie` headers?

### ISSUE THREAD

**Issue by ioquatix** [igrigorik/http-2#127]
When proxying, say, HTTP/1.1, it's possible to receive a response with multiple `set-cookie` headers. How does this work in HTTP/2 and in this gem?

Do we need to do something to handle this?

**Comment by igrigorik** [comment]
Yes, per HTTP spec you can have multiple headers with the same name. The semantics of how such values are processed are up to the particular header. In case of Set-Cookie all values are processed. 

Nothing h2 specific here.

**Comment by ioquatix** [comment]
Okay, great. I did end up looking through the code and it seem straight forward. I wasn't sure if it used a hash or an array of `[key, value]` pairs, but it's the latter.
