### ISSUE TITLE
release 0.9.1 with warning fixes

### ISSUE THREAD

**Issue by ioquatix** [igrigorik/http-2#130]
Please? thanks :)

**Comment by igrigorik** [comment]
It doesn't need to block, but I was hoping we could resolve https://github.com/igrigorik/http-2/pull/126 (and https://github.com/igrigorik/http-2/pull/44), before doing next release? WDYT?

**Comment by ioquatix** [comment]
IMHO, that's going to be a 0.10.0 release because it's going to break the contracts of the API. So far I'm aware that at least two people have worked around that bug by manually calling that function. I am happy to work on it further, but let's just get 0.9.1 out the door. I like small incremental releases.

**Comment by igrigorik** [comment]
Fair enough.

**Comment by igrigorik** [comment]
0.9.1 should be live on rubygems! https://github.com/igrigorik/http-2/commit/c3e573355b7b799f8c82d9c9d64f1fb8599ca7b2.
