### ISSUE TITLE
Gem is not fully compliant with RFC7540 Chapter 8 requirements on request/response headers.

### ISSUE THREAD

**Issue by byronformwalt** [igrigorik/http-2#137]
**Synopsis:**  [RFC7540 Chapter 8](https://httpwg.org/specs/rfc7540.html#HTTPLayer) details many requirements on client/server behavior with regard to how headers are generated and processed for requests and responses.  Several of these requirements have recently been identified as areas of non-compliance for the latest version of the http-2 gem in PR #136 .  The purpose of this issue is to collaboratively identify areas of noncompliance and to build consensus on a path to full compliance for within the scope of headers.

**Comment by igrigorik** [comment]
Believe we resolved this in linked PR, closing.

**Comment by byronformwalt** [comment]
ThanksSent from my mobile phone.On Mar 1, 2024, at 23:31, Ilya Grigorik ***@***.***> wrote:﻿
Believe we resolved this in linked PR, closing.
