### ISSUE TITLE
This repo has no a license.

### ISSUE THREAD

**Issue by xiejiangzhi** [igrigorik/http-2#145]
We need it. Please make a copyright, thanks.

**Comment by xiejiangzhi** [comment]
Ah.. I see it in the README. 
Maybe create a license file is better.

**Comment by igrigorik** [comment]
We declare the [license in the gemspec](https://github.com/igrigorik/http-2/blob/master/http-2.gemspec#L13) — see [docs](https://guides.rubygems.org/specification-reference/#license=).

Does that address it?

**Comment by xiejiangzhi** [comment]
Thanks for your answer.
For me, there is no problem. I'll close the issue.

![image](https://user-images.githubusercontent.com/1396853/53250194-dda4dc80-36f4-11e9-8277-c0c25fc52456.png)
On Github, if we have a `LICENSE` file in the root folder, it will show a license link.
Please add it if you have time. Thanks again.

**Comment by igrigorik** [comment]
@xiejiangzhi ah, good call. Added LICENSE file.
