### ISSUE TITLE
ignoring frame size negotiation

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#151]
Coming from: https://gitlab.com/honeyryderchuck/httpx/issues/59 .

If you look at the shown frame negotiation, you can see that the server negotiates an increase of max frame size. However, this is never taken into account, as data frame parsing fails with `common_header': Frame size is too large: 95846 (HTTP2::Error::CompressionError)`.

The main offender seems to be this condition, which doesn't do a thing.

**Comment by igrigorik** [comment]
Resolved via #157.
