### ISSUE TITLE
Cannot send WINDOW_UPDATE for connection

### ISSUE THREAD

**Issue by mad-p** [igrigorik/http-2#27]
Connection does not have a mechanism to send `WINDOW_UPDATE`.
Crafting a `WINDOW_UPDATE` frame and giving it to `send` method doesn't work, 
because send is private.

Suggestion:
- add `window_update` method to `Connection` (and stream), or
- make `send` public

(Wilder idea: create a pseudo-stream object that corresponds to connection-level flow control,
and make it accessible from application.  Caution: state management should be overridden by nop)

**Comment by mad-p** [comment]
OK, these were what I removed when I start implementing flow control separated inbounds/outbounds.

I want to draft a new API that can update incoming flow control and check outgoing.

**Comment by igrigorik** [comment]
Hmm... the initial window size is initialized based on provided connection settings (or spec defaults), and windows are automatically maintained based on sent/received data. When/why would you send manual window updates?

**Comment by mad-p** [comment]
Right.
This gem's API used to demand callers' responsibility of using `window` method.
Now we could automate it for application developers.
I want to look into how other implementations do (nghttp2, h2o, etc.).

**Comment by igrigorik** [comment]
@mad-p not sure I follow. We already automate window management for them... right? So, what's missing?

**Comment by mad-p** [comment]
There are two flow controls per one stream. Inbound and outbound.
We provide automatic window management for outbound `DATA` frames.
(That means, when window is full, we stop until the peer sends `WINDOW_UPDATE`.)

For inbound `DATA`, we provide house keeping but no automatic mechanism to send WU.
We could send WU when `emit(:data)` returned, assuming that the application can receive next `emit(:data)` by now. 
Do we need a configuration whether this automation is enabled/disabled?

**Comment by igrigorik** [comment]
> For inbound DATA, we provide house keeping but no automatic mechanism to send WU.
> We could send WU when emit(:data) returned, assuming that the application can receive next emit(:data) by now. Do we need a configuration whether this automation is enabled/disabled?

Ah.. I'm with you know - thanks! This seems like an implementation oversight and +1 for automatically emitting a WU frame after emit(:data) is processed. I wouldn't worry about the on/off for automation for now: start with automation, wait for use cases and explicit requests to implement own?

**Comment by mad-p** [comment]
That makes sense.  I'll write a to-do list before writing code.

**Comment by mad-p** [comment]
Here is a to-do list to support inbound flow-control:
- add window_update method to both Session and Connection
- automatic WU after emit(:data)
- correctly handle padding length in calculating the window size (currently not)

**Comment by igrigorik** [comment]
:+1:

**Comment by tbetbetbe** [comment]
Is tbetbetbe/http-2@0047115bdddb096b5e26ac313f018a8c342a84d3 where this is headed ?
@mad-p, if you want I can add tests to these changes and submit it as a PR.

> correctly handle padding length in calculating the window size
If you clarify what this means, I can add this as well, otherwise perhaps this can go in a separate PR?

**Comment by mad-p** [comment]
@tbetbetbe: my WIP is in https://github.com/lepidum/http-2/commit/c37100ca80db64f24704c9e86a90f72a5d9528f7 .

Good catch :remote_closed

I'd add some tests with padded DATA frames.

**Comment by igrigorik** [comment]
@mad-p any updates on this one? :)

**Comment by igrigorik** [comment]
@mad-p @tbetbetbe this is a blocking issue for https://github.com/igrigorik/http-2/issues/57, can we pull it over the line? 

Reviewing https://github.com/lepidum/http-2/commit/c37100ca80db64f24704c9e86a90f72a5d9528f7 and https://github.com/tbetbetbe/http-2/commit/0047115bdddb096b5e26ac313f018a8c342a84d3:

- @mad-p's patch accounts for padding
- @tbetbetbe's patch accounts for remote closed state

Either one of you willing to merge the two? If not, I can land one of your forks and update it on this end.

**Comment by igrigorik** [comment]
Resolved via https://github.com/igrigorik/http-2/pull/107
