### ISSUE TITLE
Example with priorities

### ISSUE THREAD

**Issue by sanxzkid** [igrigorik/http-2#31]
There is any example with HTTP/2 in Ruby serving a HTML file with prioritization of resources?

**Comment by igrigorik** [comment]
No. There is a very simple server implementation in `examples` directory that can be extended to do that though. Each stream has a corresponding dependency and weight attribute that you can query to figure out the optimal prioritization:

- http://www.rubydoc.info/github/igrigorik/http-2/HTTP2/Stream#dependency-instance_method
- http://www.rubydoc.info/github/igrigorik/http-2/HTTP2/Stream#weight-instance_method

**Comment by sanxzkid** [comment]
I want to test performance with and without prioritization in load page, but example as too simple and existent implementations in real word ( like twitter, google, ... ) don't have away to turn ON/OFF this property.

My idea was load a web page with a lot of figures but server example doesn't load in any browser too.

**Comment by igrigorik** [comment]
I'd suggest you take a look at h2o or nghttp, they're fully fledged servers that support all the features you're looking for. http-2, on the other hand, is a low level library that allows you build such a server.. :)
