### ISSUE TITLE
Does http-2 work with ruby-1.9.3 ?

### ISSUE THREAD

**Issue by lowks** [igrigorik/http-2#42]
When I try to run `require 'http/2'` in ruby-1.9.3 I get the following error:

SyntaxError: /home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:97: syntax error, unexpected tPOW, expecting ')'
      def initialize(**options)
                       ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:303: dynamic constant assignment
    HEADREP = {
             ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:313: dynamic constant assignment
    NAIVE    = { index: :never,  huffman: :never   }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:314: dynamic constant assignment
    LINEAR   = { index: :all,    huffman: :never   }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:315: dynamic constant assignment
    STATIC   = { index: :static, huffman: :never   }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:316: dynamic constant assignment
    SHORTER  = { index: :all,    huffman: :never   }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:317: dynamic constant assignment
    NAIVEH   = { index: :never,  huffman: :always  }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:318: dynamic constant assignment
    LINEARH  = { index: :all,    huffman: :always  }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:319: dynamic constant assignment
    STATICH  = { index: :static, huffman: :always  }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:320: dynamic constant assignment
    SHORTERH = { index: :all,    huffman: :shorter }.freeze
              ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:323: class definition in method body
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:325: syntax error, unexpected tPOW, expecting ')'
      def initialize(**options)
                       ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:465: class definition in method body
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:467: syntax error, unexpected tPOW, expecting ')'
      def initialize(**options)
                       ^
/home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2/compressor.rb:555: syntax error, unexpected keyword_end, expecting $end
from /home/lowks/.rvm/gems/ruby-1.9.3-p551/bundler/gems/http-2-025812598a71/lib/http/2.rb:8:in `require'

**Comment by amitsaxena** [comment]
+1. I got the same error.

**Comment by igrigorik** [comment]
Thanks for reporting this. We do leverage 2.0.0 features and given that [1.9.3 is now deprecated](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), I think this is wontfix.

**Comment by igrigorik** [comment]
Added in https://github.com/igrigorik/http-2/commit/b8fbf9380ac4a8dfed0ff6511fd5c35668cb9964.
