### ISSUE TITLE
How to set a request timeout?

### ISSUE THREAD

**Issue by ostinelli** [igrigorik/http-2#49]
Hi,
I couldn't find a way to set the timeout for a request (frame). Can you please point me in the right direction?

Thank you,
r.

**Comment by igrigorik** [comment]
There is no built-in timeout mechanism in HTTP or the http-2 library. That said, with h2 you can send a RST_STREAM to reset a stream.. say, if your own timer has expired. 

As such, you can any timer mechanism you want in Ruby to start + trigger the RST_STREAM.

**Comment by ostinelli** [comment]
Indeed there is no such mechanism, but most libraries allow you (one way or another) to easily set a timeout on requests. Since the http-2 is abstracted from the transport, it is less obvious to do so - and wanted to confirm with you that this wasn't there.

Thank you.
