### ISSUE TITLE
Errors eaten by lib when running threaded

### ISSUE THREAD

**Issue by ostinelli** [igrigorik/http-2#50]
Hello,
First of all - thank you for providing the first ruby HTTP/2 library.

I'm trying to implement a realistic client example that uses your library. The one you provide is great, however it is missing the practical scenario of having a client socket continuously listening for incoming responses and events (to my understanding, basically HTTP/2 requires 2-way sockets), while still allowing library users to send out frames.

One possible choice is to have a thread dedicated to listening, so I have coded a very simple example on how to do so. However, any errors that are generated in the thread appear to be eaten up by the library.

Try this code:

```ruby
require 'socket'
require 'uri'
require 'http/2'

class Client

  def initialize
    @uri = URI.parse("http://106.186.112.116")

    @socket      = nil
    @read_thread = nil

    ensure_socket
  end

  def get
    headers = {
      ':scheme' => @uri.scheme,
      ':method' => 'GET',
      ':path'   => "/",
      'host'    => @uri.host
    }
    stream  = h2.new_stream

    ensure_socket

    stream.headers(headers, end_stream: true)

    receive
  end

  def ensure_socket
    return if @socket

    @socket = TCPSocket.new(@uri.host, @uri.port)

  rescue SocketError => e
    puts "Could not connect to socket (#{e.class} exception: #{e.message})"
    close
  end

  def h2
    @h2 ||= HTTP2::Client.new.tap do |h2|
      h2.on(:frame) do |bytes|
        puts "Sending bytes: #{bytes.unpack("H*").first}"
        @socket.print bytes
        @socket.flush
      end

      h2.on(:frame_sent) do |frame|
        puts "Sent frame: #{frame.inspect}"
      end

      h2.on(:frame_received) do |frame|
        puts "Received frame: #{frame.inspect}"

        # raise "EXPLODE HERE"
      end
    end
  end

  def receive
    return if @read_thread

    @read_thread = Thread.new do
      loop do
        begin
          data = @socket.read_nonblock(1024)
        rescue Errno::EAGAIN
          retry
        end

        begin
          h2 << data
        rescue => e
          puts "#{e.class} exception: #{e.message} - closing socket."
          e.backtrace.each { |l| puts "\t" + l }
          close
        end

        break unless @socket && !@socket.closed? && !@socket.eof?
      end

      close
    end

    @read_thread.abort_on_exception = true
  end

  def close
    @socket.close if @socket && !@socket.closed?
    @read_thread.exit if @read_thread

    @socket      = nil
    @h2          = nil
    @read_thread = nil
  end
end

c = Client.new
c.get

while true
  sleep 1
end
```

Run it as is, and this will issue a `GET` request to the http://106.186.112.116 test server. Everything should just work, and you will see the response frames. You can also issue multiple `c.get` instructions, and they all will work.

Now, uncomment the line `# raise "EXPLODE HERE"` and run again. You will see the following:

```
HTTP2::Error::ProtocolError exception: HTTP2::Error::ProtocolError - closing socket.
	/Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:650:in `connection_error'
	/Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:324:in `rescue in receive'
	/Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:163:in `receive'
	test.rb:75:in `block (2 levels) in receive'
	test.rb:67:in `loop'
	test.rb:67:in `block in receive'
```

Obviously this isn't the error that one would like to see in the logs.

Do you have any recommendations to fix this, or an example of a realistic client that can keep on listening for server events?

Thank you,
r.

**Comment by igrigorik** [comment]
Have you tried this against master? We recently landed some updates that are not in stable release yet that should address this: https://github.com/igrigorik/http-2/commit/d62b80ad5ea248380581f76b968a74c74fb49193

**Comment by ostinelli** [comment]
Yes, the error is still eaten up when using the example above.

**Comment by igrigorik** [comment]
```
Sending bytes: 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
Sent frame: {:type=>:settings, :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100]]}
Sending bytes: 000006040000000000000300000064
Sent frame: {:type=>:headers, :flags=>[:end_headers, :end_stream], :payload=>[[":scheme", "http"], [":method", "GET"], [":path", "/"], ["host", "106.186.112.116"]], :stream=>1}
Sending bytes: 000010010500000001868284668b081c5c2f38b84225c2173f
[:receive, "", "\x00\x00\f\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00d\x00\x04\x00\x00\xFF\xFF"]
Received frame: {:length=>12, :type=>:settings, :flags=>[], :stream=>0, :payload=>[[:settings_max_concurrent_streams, 100], [:settings_initial_window_size, 65535]]}
[:connection_error, :protocol_error, nil, "/Users/igrigorik/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/http-2-0.8.0/lib/http/2/connection.rb:331:in `rescue in receive'\n/Users/igrigorik/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/http-2-0.8.0/lib/http/2/connection.rb:163:in `receive'\nclient-thread.rb:74:in `block (2 levels) in receive'\nclient-thread.rb:66:in `loop'\nclient-thread.rb:66:in `block in receive'"]
Sent frame: {:type=>:goaway, :last_stream=>1, :error=>:protocol_error, :payload=>nil}
Sending bytes: 0000080700000000000000000100000001
HTTP2::Error::ProtocolError exception: HTTP2::Error::ProtocolError - closing socket.
	/Users/igrigorik/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/http-2-0.8.0/lib/http/2/connection.rb:658:in `connection_error'
	/Users/igrigorik/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/http-2-0.8.0/lib/http/2/connection.rb:331:in `rescue in receive'
	/Users/igrigorik/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/http-2-0.8.0/lib/http/2/connection.rb:163:in `receive'
	client-thread.rb:74:in `block (2 levels) in receive'
	client-thread.rb:66:in `loop'
	client-thread.rb:66:in `block in receive'
```

The above is generated due to the rescue block in your thread loop:

```
        begin
          h2 << data
        rescue => e
          puts "#{e.class} exception: #{e.message} - closing socket."
          e.backtrace.each { |l| puts "\t" + l }
          close
        end
```

If you remove that, everything works as expected.. Well, as in, it crashes :)

**Comment by ostinelli** [comment]
@igrigorik, the issue is not whether it crashes or not :) The issue here is that the _reason_ why a failure happens gets eaten up by the gem.

If I remove the rescue block, I get:
```
Sending bytes: 0000080700000000000000000100000001
/Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:650:in `connection_error': HTTP2::Error::ProtocolError (HTTP2::Error::ProtocolError)
	from /Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:324:in `rescue in receive'
	from /Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:163:in `receive'
	from test.rb:74:in `block (2 levels) in receive'
	from test.rb:66:in `loop'
	from test.rb:66:in `block in receive'
```
As you can see, here too we get a `HTTP2::Error::ProtocolError` reported. The problem, though, is that it should be `EXPLODE HERE`, since _this_ is the error that I raised.

Using this gem as is hard because it means that _any_ error in the code built around your gem will result in a `HTTP2::Error::ProtocolError`, which hides whatever real error generated it. 

Hopefully this clarifies what I mean with errors being "eaten up". :)

**Comment by ostinelli** [comment]
I suspect [this](https://github.com/igrigorik/http-2/blob/3bf07b9e4643b50aee5f6ace5c4ca9cf31723bab/lib/http/2/connection.rb#L322) is where it all happens.

**Comment by igrigorik** [comment]
@ostinelli apologies about the delay! Running the above code, with latest code in master, I see:

```
HTTP2::Error::ProtocolError exception: EXPLODE HERE - closing socket.
	example/test.rb:59:in `block (2 levels) in h2'
	/Users/igrigorik/git/http-2/lib/http/2/emitter.rb:34:in `call'
	/Users/igrigorik/git/http-2/lib/http/2/emitter.rb:34:in `block in emit'
	/Users/igrigorik/git/http-2/lib/http/2/emitter.rb:33:in `delete_if'
	/Users/igrigorik/git/http-2/lib/http/2/emitter.rb:33:in `emit'
	/Users/igrigorik/git/http-2/lib/http/2/connection.rb:190:in `receive'
	example/test.rb:76:in `block (2 levels) in receive'
	example/test.rb:68:in `loop'
	example/test.rb:68:in `block in receive'
```

I think that's what you want, no?

**Comment by ostinelli** [comment]
Yes! Thank you @igrigorik!

**Comment by igrigorik** [comment]
Cool, glad it's working! I'll try to push out a new release within the next week (want to take a pass over a  few other issues first).

**Comment by ostinelli** [comment]
Hi @igrigorik, I didn't try it out until now. Unfortunately no, it's not working: the above code still produces the same:

```
/Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:650:in `connection_error': HTTP2::Error::ProtocolError (HTTP2::Error::ProtocolError)
	from /Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:324:in `rescue in receive'
	from /Users/roberto/.rvm/gems/ruby-2.3.0@apnotic/gems/http-2-0.8.0/lib/http/2/connection.rb:163:in `receive'
	from test.rb:76:in `block (2 levels) in receive'
```

**Comment by ostinelli** [comment]
Scratch that, my bad. It works as intended. Thank you!

**Comment by ostinelli** [comment]
Wanted to thank you for this fix, and let you know your gem is used here:
https://github.com/ostinelli/apnotic

:)

Best,
r.

**Comment by igrigorik** [comment]
That looks really nice -- great stuff! Let me know if you come across any other issues.

**Comment by ostinelli** [comment]
BTW: I couldn't find any HTTP2 client for ruby so... your work is now also included in this new gem: https://github.com/ostinelli/net-http2

:)

**Comment by igrigorik** [comment]
Ha! You've been busy.. :)

Nice work! Reading through the code..
- there is no way to pass through request priorities, right?
- response streaming? It'd be nice to have a way to consume it without buffering the whole response.
- hook for receiving server push?

I guess I should probably leave these as issues on the repo..

**Comment by ostinelli** [comment]
> * there is no way to pass through request priorities, right?
> * response streaming? It'd be nice to have a way to consume it without buffering the whole response.
> * hook for receiving server push?

All of these are in my TODO. I've currently put the main effort on the "classical" HTTP/1 support, will add all async stuff soon.

> I guess I should probably leave these as issues on the repo..

If you could it would be awesome. I'll definitely track them down.

PS: didn't mean to hijack your repo! Just wanted to ensure you knew your work was appreciated and used :)
