### ISSUE TITLE
Documentation for the promise?

### ISSUE THREAD

**Issue by georgeu2000** [igrigorik/http-2#58]
Thank you for all your awesome work on HTTP2. 

The following code from the docs seems strange:
```
  head = {
     ":status" => 200,
     ":path"   => "/other_resource",
     "content-type" => "text/plain"
    }

    # initiate server push stream
    stream.promise(head) do |push|
      push.headers({ ... })
      push.data(...)
    end

    # send response
    stream.headers({
      ":status" => 200,
      "content-type" => "text/plain"
    })

    # split response between multiple DATA frames
    stream.data(response_chunk, end_stream: false)
    promise.data(payload)
    stream.data(last_chunk)
```

It's not clear what data would be pushed in the promise. According to [HPBN](https://hpbn.co/http2/#push-promise-101)

> PUSH_PROMISE frames, which signal the server’s intent to push the described resources to the client and need to be delivered ahead of the response data that requests the pushed resources.

What data would be sent in the PUSH_PROMISE if the data is supposed to be sent later?

Also, `promise` is not defined at this point: `promise.data(payload)`. Is this supposed to refer to the promise stream? If so, how to access it? Or are the promise and the response stream the same? In that case, would it be `stream.data(promise_data)`?

**Comment by igrigorik** [comment]
> What data would be sent in the PUSH_PROMISE if the data is supposed to be sent later?

PUSH_PROMISE delivers headers meta-data about the resource you're promising to push, thus notifying the client that if it wants to fetch this resource.. it should hold-on because the server is already planning to send it this data (when exactly is at the discretion of the server). 

> Also, promise is not defined at this point: promise.data(payload). Is this supposed to refer to the promise stream? If so, how to access it? 

Yes, you're right that's a bug. It should refer to the "push" stream established above.

> Or are the promise and the response stream the same? In that case, would it be stream.data(promise_data)?

No, they're *not* the same stream. When you call .promise you get back a new stream: https://github.com/igrigorik/http-2/blob/master/lib/http/2/server.rb#L118

**Comment by georgeu2000** [comment]
OK, thanks for the info.

How can I contribute?

**Comment by igrigorik** [comment]
@georgeu2000 any and all code/documentation/example patches (pull requests) would be most welcome! I could have sworn I had a push example lying around.. but I think I accidentally wiped it before I committed it. Having a working h2 push example would be a great contribution.. if you're up for it :)
