### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by georgeu2000** [igrigorik/http-2#59]
This [commit](https://github.com/georgeu2000/http-2/commit/677774f1b4c61bbe9c8ea01a27d5b38eef6dda6b) introduced a syntax error:

`+    def initialize(connection:, id:, weight: 16`

```
/Users/george/repos/http-2/lib/http/2/stream.rb:74: syntax error, unexpected ',' (SyntaxError)
...    def initialize(connection:, id:, weight: 16, dependency:
```

I can fix the syntax errors (with `nil`), but this commit also removes ArgumentErrors. I didn't know if they should be removed.

If we need the ArgumentErrors, the we can revert the whole commit.

**Comment by georgeu2000** [comment]
I see that this is a syntax error on Ruby 2.0, but not Ruby 2.3.1.

Shall we add "Tested on Ruby 2.3.1" in the Readme, and set it in the Gemfile?

**Comment by igrigorik** [comment]
In theory, that should already be enforced via: https://github.com/igrigorik/http-2/blob/master/http-2.gemspec#L15

**Comment by georgeu2000** [comment]
Oh, I see. Thanks.
