### ISSUE TITLE
Dual Protocol Server

### ISSUE THREAD

**Issue by TiagoCardoso1983** [igrigorik/http-2#71]
I'm exploring this library for a ruby server which could serve both http 1 and 2. I saw the upgrade script, so my question would also be if this (dual-version serving) would be a reasonable idea, or whether one should just go full-http2 and upgrade all connections. My assumption is this is not a good idea, as a lot of clients just can't be upgraded to http2 due to dependency constraints (no compatible openssl, old kernel, old curl). But if my assumption is correct, what is the best way to identify the version? 

I was thinking something like "read some data, check what's the advertised version in the first line, and continue accordingly". Is there a more correct way of doing this, or am I going in the right direction?

**Comment by georgeu2000** [comment]
It depends on the client. Most browsers only support HTTP/2 with TLS. If it is a browser, then HTTP/2 will be negotiated with TLS. You can manager that here: https://github.com/igrigorik/http-2/blob/master/example/server.rb#L34-L37 .

If it needs to work with all clients, then you can check for the Upgrade header. Here is some info: https://hpbn.co/http2/#upgrading-to-http2

**Comment by igrigorik** [comment]
As @georgeu2000 said.. If you're targeting browsers, then they will only negotiate h2 over TLS and the supported version will be in the handshake (if they support ALPN). You definitely don't need to sniff any bytes.

**Comment by TiagoCardoso1983** [comment]
I'm still in exploratory phase, so I don't know what makes more sense in production, expose the ruby server HTTP1/2-over-SSL or do SSL termination in the web server and send HTTP1/2 traffic to the ruby server unencrypted. The second one could be a possible migration path, as deployments are usually that way. I'll check in the provided links for more info and come up with results. Thank you for the library and the supported!

**Comment by igrigorik** [comment]
Sounds good. Closing this, as this is not an lib issue.. please feel free to reopen if you come across any issues/questions.

**Comment by TiagoCardoso1983** [comment]
I've found some time to study the upgrade server example script. It seems that the `UpgradeHandler` is [getting away by sniffing the bytes](https://github.com/igrigorik/http-2/blob/bf4b930c19934521bb0ffcfa19486ff7e415ed55/example/upgrade_server.rb#L170).  

I'm just confused a bit [with this part](https://github.com/igrigorik/http-2/blob/bf4b930c19934521bb0ffcfa19486ff7e415ed55/example/upgrade_server.rb#L170-L175), which seems to buffer the data either to the upgrader or to the http2 connection/server (what's the purpose of naming an http connection `HTTP2::Server`?) depending of the connection header.
It seems that the example is only able to handle HTTP1.1 "upgrade to h2c" requests, ignoring every other possible HTTP1.1 request type. Is my assumption correct? If so, technically, it would be easy to extend that handler to support non-upgrade HTTP1.1 requests.

**Comment by igrigorik** [comment]
> It seems that the example is only able to handle HTTP1.1 "upgrade to h2c" requests, ignoring every other possible HTTP1.1 request type. Is my assumption correct? If so, technically, it would be easy to extend that handler to support non-upgrade HTTP1.1 requests.

Yes. It's a demo server for the H1 -> H2 upgrade, nothing more..

**Comment by TiagoCardoso1983** [comment]
Thx for the help, I think I have what I need. For future questions, is a github issue the proper way to ask a question, or is there smth like, like a google group, for the project?

**Comment by igrigorik** [comment]
Github is good :)
