### ISSUE TITLE
Proxy layer

### ISSUE THREAD

**Issue by Nattfodd** [igrigorik/http-2#79]
While original Net::HTTP has Proxy subclass, it would be nice to have access to same thing for http/2 protocol. Any ideas on this?

**Comment by igrigorik** [comment]
Not sure that this belongs in http-2.. Our library intentionally does *not* implement connection handling, allowing you to plug and play different transports. Nothing stops you from layering this over an HTTP proxy / SOCKS proxy / whatever, but that's out of scope for this lib.
