### ISSUE TITLE
Server-Push: how to properly not push when user has a resource cached

### ISSUE THREAD

**Issue by TiagoCardoso1983** [igrigorik/http-2#85]
I'm building an API for server-push. It works if I just push 200+data, but this seems inefficient for when the user already has the resource in the cache. HTTP1 has the Etag/Last-Modified mechanism, but I don't know how to build the same behaviour for HTTP2/server-push. Specifically I've been looking at [this documentation](https://w3c.github.io/preload/#server-push-http-2) and [this example](https://nghttp2.org/blog/2015/02/10/nghttp2-dot-org-enabled-http2-server-push/). I'm using Chrome 54, and analysing the http headers with the developer tools doesn't show me any `link` header. Am I missing something?

I've built an [example](https://github.com/TiagoCardoso1983/jaguar/blob/master/examples/bootstrap-app.rb) to demonstrate. The push itself is not working as expected, as the response headers are sent, push headers are sent, response data is sent, push data is sent, but the first thing I get after is a request for the same resource I just pushed. I'm assuming I'm misusing the API?
But in the end, the intended goal of the example would be to push the css file, and send 304 if it is cached in the client. How to best do it?

**Comment by igrigorik** [comment]
> I'm building an API for server-push. It works if I just push 200+data, but this seems inefficient for when the user already has the resource in the cache. HTTP1 has the Etag/Last-Modified mechanism, but I don't know how to build the same behaviour for HTTP2/server-push.

ETag and Last-Modified apply to both h1 and h2. The difference is that with server push the server is able to push a response **before** the client sends the (revalidation) request. How does the server know? There is no definitive answer for that, but [cache digests](https://tools.ietf.org/html/draft-ietf-httpbis-cache-digest-01) proposal might be worth checking out.

> Specifically I've been looking at this documentation and this example. I'm using Chrome 54, and analysing the http headers with the developer tools doesn't show me any link header. Am I missing something?

That directive is something *your server* needs to process. My application sets the header, your server sees it and initiates push on my behalf. Chrome doesn't apply any magic here.

> I've built an example to demonstrate. The push itself is not working as expected, as the response headers are sent, push headers are sent, response data is sent, push data is sent, but the first thing I get after is a request for the same resource I just pushed. I'm assuming I'm misusing the API?

Check chrome://net-internals for the full log. It sounds like your push'ed response is not being matched with the later request.

---

None of the above is http-2 lib specific, closing..

**Comment by TiagoCardoso1983** [comment]
> There is no definitive answer for that, but cache digests proposal might be worth checking out.

So there is no current strategy for production deployment, did I understand correctly? I will read the rfc. I was also thinking, if the main page is responded with 304, one could assume cached assets as well.  But this is not a sure guarantee, so yeah, I think other minds have put more time in the problem than I could. 

> That directive is something your server needs to process. 

I assume that by my server, you mean that the response from the application comes with the link headers, and I just have to read/interpret and initiate push promise streams myself. But since I'm passing around ruby objects, I don't need to do it ad-hoc, right? But then again, I could 
send them as response link headers to a possible reverse proxy (nginx, apache), which would interpret them and initiate push responses themselves. In a different scenario, I could open/reuse a socket to a CDN, request a resource and pipe it as push response to the client. Are these the intended cases? Is the link header a way to communicate through a proxy which serves assets?

>  It sounds like your push'ed response is not being matched with the later request.

I do see 1 pushed, 0 pushed and claimed. What can I do about it, and how could I debug this further? Do you have any resources you could point me to?

As always, thx for the thorough support.

**Comment by igrigorik** [comment]
Server push is successfully used in production.. But there is no "magic oracle mechanism" that will tell you if the client already has the resource in their cache. See: https://hpbn.co/optimizing-application-delivery/#eliminate-roundtrips-with-server-push

> send them as response link headers to a possible reverse proxy (nginx, apache), which would interpret them and initiate push responses themselves. In a different scenario, I could open/reuse a socket to a CDN, request a resource and pipe it as push response to the client. 

Yes, as long as your upstream server understands such Link headers. AFAIK, nginx does not. Apache with latest mod_http2 does.

> What can I do about it, and how could I debug this further? Do you have any resources you could point me to?

Make sure push promises arrive before request is initiated; that resource paths match, etc.

**Comment by TiagoCardoso1983** [comment]
>  But there is no "magic oracle mechanism" that will tell you if the client already has the resource in their cache. 

But until it comes (I assume, the CACHE_DIGEST frame proposal aims at being the magic oracle), would you say that "send request with etag -> get 304 empty response" is surpassed by "eliminate roundtrip send 200 + payload"? I just want to understand my options here, although I understand this is still a work in progress. 

> AFAIK, nginx does not.

Ouch. so I guess there's no way currently to set up a ruby app behind an nginx reverse-proxy without resorting to HTTP2-termination. Good to know. 

Regarding the bug, I managed to fix it. Turns out, nghttp in verbose mode is very helpful. 

Thx!

**Comment by igrigorik** [comment]
> But until it comes (I assume, the CACHE_DIGEST frame proposal aims at being the magic oracle), would you say that "send request with etag -> get 304 empty response" is surpassed by "eliminate roundtrip send 200 + payload"? I just want to understand my options here, although I understand this is still a work in progress.

It depends on what's more important to you: latency or bytes. There are cases where you might be willing to incur extra bytes regardless of whether client already has resource or not; in other cases, you might want to be extra careful to avoid unnecessary bytes on the wire.
