### ISSUE TITLE
Client: Upgrade protocol

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#94]
Not as much an issue, but a currently non-existing feature request with a possible solution. The `upgrade_server.rb` example has been tested using nghttp and adds an `#upgrade` method to `HTTP2::Server`. A matching method doesn't exist for the client, which is, granted, not such a relevant feature. But I've been needing an implementation to test my workflow, and have come up with the following solution:

```ruby
def upgrade(data: )
  @connection.send_connection_preface
  stream = @connection.new_stream
  stream.on(:headers) ...
  @connection << data if data
end
```

This method is called after an established "HTTP1 upgrade to H2C" session socket is already around. Connection preface is sent immediately, as by the spec (although the spec states that the connection is therefore in half_closed mode, not sure how much of it internally is like that). After, stream 1 is created, along with the callbacks. The last line are frame remaining in the http1 socket buffer (I've been using net/http in my tests, and it makes it impossible to access the buffer using public API). 

Do you think that such a think is worth to be added, or maybe documented in an example (granted, if I make it work with the example upgrade server :) )?

**Comment by kenichi** [comment]
@HoneyryderChuck as one who worked on the upgrade stuff previously, i think this is a great example. i backed off supporting upgrade paths in my branch of [reel](https://github.com/kenichi/reel/tree/h2/lib/reel/h2) since no browsers support it and probably won't, but i like the idea of at least having it documented as an example.

**Comment by HoneyryderChuck** [comment]
@kenichi thanks for the feedback. I think this is relevant to this library in particular because 1) it aims to be a reference implementation, and 2) it would make for a good version-agnostic http client library or event ruby-based HTTP 1-to-2 proxy (I think these will be massive implementation cases for non-encrypted HTTP2 deployments). 
I have the described specification working in my tests, just trying to get the semantics right, and will be looking forward to some relevant inputs.

**Comment by igrigorik** [comment]
@HoneyryderChuck can we resolve this now with #99 in place?

**Comment by HoneyryderChuck** [comment]
@igrigorik it does.

**Comment by igrigorik** [comment]
Cool. Thanks again!
