### ISSUE TITLE
Closing a connection: how to safely close

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#96]
The examples are not very specific on this, so I have to ask: how should one know for sure that it's safe to terminate the socket on the server side, or inform the server to terminate on the client side?

The way I see it, and since there is already a callback for that, one has to:

* client: send a goaway frame and terminate the socket
* server: set a `on(:goaway)` callback , and terminate the socket. 

Is such an usage deviating from the http2 spec?

**Comment by igrigorik** [comment]
Yep..

- On the client, call close() on the connection, which will send the goaway frame.
- On the server, listen for the goaway frame: finish processing any inflight streams and then close the connection. 

More here: https://tools.ietf.org/html/rfc7540#section-6.8

**Comment by HoneyryderChuck** [comment]
Thx for the reply, I see now I have missed. On the server side, I have to somehow keep a tab on the in-flight streams, process the goaway with the last stream, close socket if possible, or wait for last stream and lower ones to finish processing before I terminate the socket. 

On the client, I didn't quite get it. You mention close(), but there is no such method (only goaway). Also, you didn't mention the client-side socket: is it safe to close after sending goaway, or do I have to have some similar logic for processing in-flight streams before safely terminating?

**Comment by igrigorik** [comment]
> Thx for the reply, I see now I have missed. On the server side, I have to somehow keep a tab on the in-flight streams, process the goaway with the last stream, close socket if possible, or wait for last stream and lower ones to finish processing before I terminate the socket.

Yep.

> On the client, I didn't quite get it. You mention close(), but there is no such method (only goaway). 

Ah, my bad.. yes, use goaway to indicate that you want to terminate the connection. :-)

> Also, you didn't mention the client-side socket: is it safe to close after sending goaway, or do I have to have some similar logic for processing in-flight streams before safely terminating?

Depends on the context. If you have an unfinished stream but want to indicate to the server that you want to terminate the connection after that's finished, then you should keep the client socket open until you received all the data.. On the other hand, if you have all the data, or don't care for the rest, you can close the socket immediately.

**Comment by HoneyryderChuck** [comment]
gotcha! as the client is not as important to me, I'll be more "liberal" with it. Thx again!
