### ISSUE TITLE
Feature: Provide helper to build http2-settings header (for h2c)

### ISSUE THREAD

**Issue by HoneyryderChuck** [igrigorik/http-2#99]
As of now, it is only possible to encode full frames with the current API:

```ruby
# inside connection
frame = {type: :settings, ...}
encode([frame])....
```

Which is fine for most uses. However, the `h2c` spec allows for encoding client setting in the `HTTP2-settings` frame. This is not the full frame, but only the payload part. This is [a few layers down in the framer](https://github.com/igrigorik/http-2/blob/master/lib/http/2/framer.rb#L223-L235). 

I'd propose to have a public API for returning only the encoded payload of frames (maybe harder), or to add a method to the connection/client to return the payload for the `HTTP2-settings` header. This is my current workaround:

```ruby
# HTTP2 Client extension
def http2_settings
  payload = @local_settings.select { |k, v| v != HTTP2::SPEC_DEFAULT_CONNECTION_SETTINGS[k] }
  frame = { :type => :settings, :stream => 0, payload: Array(payload) }
  encode(frame).map do |f| 
    noheader_frame = f[9..-1] # remove header from http-2 frame
    Base64.urlsafe_encode64(noheader_frame)
  end.join
end	

```

**Comment by igrigorik** [comment]
Silly question.. why? As in, the only place I can see this being useful is in the H2C negotiation with the settings case, otherwise you're always emitting frames.

**Comment by HoneyryderChuck** [comment]
Yes, for that use case only. It is a not-so-important helper method, but helps in building clients that can upgrade to h2c. FWIW there's an example of an upgrade server, but one has to test it with `nghttp`. Somewhat low hanging fruit.

**Comment by HoneyryderChuck** [comment]
@igrigorik this should be taken as a step towards #94 . Long story short, if I'd want to support the h2c flow as a client using this library, I'll need things that it doesn't provide yet:

* generate the "HTTP-Settings" header for HTTP/1.1 ; 
* `HTTP2::Client` must send connection preface ;
* stream 1 must be initialized in half-closed state ;

I'd propose a client-only method for helping with the last 2, plus a helper method to help with the first one(?).

**Comment by igrigorik** [comment]
From a high-level, that makes sense. I'd need to see the API you have in mind for 2+3 for more meaningful feedback. :-)

**Comment by HoneyryderChuck** [comment]
Will have a go at it soon ;)
